module.exports = [
  "function addAdmin(address _admin) external",
  "function removeAdmin(address _admin) external",
  "function isAdmin(address _addr) external view returns (bool)",
  "function admins(address) external view returns (bool)",
  "function issueCertificate(bytes32 _hash, string _certId, string _ipfsCID, string _recipientName, string _courseName, string _issuingOrg) external",
  "function verifyCertificate(bytes32 _hash) external returns (bool exists, bool isValid, bool isRevoked)",
  "function verifyCertificateById(string _certId) external returns (bool exists, bool isValid, bool isRevoked)",
  "function revokeCertificate(bytes32 _hash, string _reason) external",
  "function getCertificate(bytes32 _hash) external view returns (tuple(bytes32 certHash, address issuer, address revokedBy, uint64 issuedAt, uint64 revokedAt, bool isRevoked, string ipfsCID, string recipientName, string certId, string courseName, string issuingOrg))",
  "function getCertificateById(string _certId) external view returns (tuple(bytes32 certHash, address issuer, address revokedBy, uint64 issuedAt, uint64 revokedAt, bool isRevoked, string ipfsCID, string recipientName, string certId, string courseName, string issuingOrg))",
  "function getVerificationHistory(bytes32 _hash) external view returns (tuple(address verifier, uint256 verifiedAt)[])",
  "function getTotalCertificates() external view returns (uint256)",
  "function getIssuedByAdmin(address _admin) external view returns (bytes32[])",
  "function getHashByCertId(string _certId) external view returns (bytes32)",
  "event CertIssued(bytes32 indexed certHash, string certId, address indexed issuer, uint256 issuedAt)",
  "event CertVerified(bytes32 indexed certHash, address verifier, uint256 verifiedAt)",
  "event CertRevoked(bytes32 indexed certHash, address indexed revoker, string reason, uint256 revokedAt)",
  "event AdminAdded(address indexed admin)",
  "event AdminRemoved(address indexed admin)",
];
